from __future__ import annotations

from dataclasses import dataclass

from .core import ActionSpec, ExplorerContext


@dataclass(frozen=True)
class AnswerState:
    answer: str
    rationale: str
    depth: int = 0
    metadata: dict[str, str] | None = None


def build_answer_prompt(
    parent_state: AnswerState | None,
    context: ExplorerContext,
) -> list[dict[str, str]]:
    if parent_state is None:
        user_content = f"""
Task:
{context.task}

Generate a candidate answer.
"""
    else:
        user_content = f"""
Task:
{context.task}

Previous answer:
{parent_state.answer}

Previous rationale:
{parent_state.rationale}

Improve the answer.
"""

    return [
        {"role": "system", "content": "You are a rigorous reasoning assistant."},
        {"role": "user", "content": user_content},
    ]


def parse_answer_state(
    raw: str,
    parent_state: AnswerState | None,
    context: ExplorerContext,
) -> AnswerState:
    return AnswerState(
        answer=raw.strip(),
        rationale="Generated by LLM action.",
        depth=0 if parent_state is None else parent_state.depth + 1,
        metadata={"profile": context.profile.value},
    )


def simple_scorer(
    state: AnswerState,
    parent_state: AnswerState | None,
    context: ExplorerContext,
) -> float:
    text = state.answer.strip()

    if not text:
        return 0.0

    length_score = min(len(text) / 2000, 1.0)
    structure_score = 1.0 if "```" in text or "#" in text else 0.7

    return max(0.0, min((length_score * 0.7) + (structure_score * 0.3), 1.0))


def default_answer_actions() -> list[ActionSpec[AnswerState]]:
    return [
        ActionSpec[AnswerState](
            name="llama_fast_draft",
            model="llama-fast",
            prompt_builder=build_answer_prompt,
            parser=parse_answer_state,
            scorer=simple_scorer,
            temperature=0.8,
            max_tokens=2048,
        ),
        ActionSpec[AnswerState](
            name="llama_precise_refine",
            model="llama-precise",
            prompt_builder=build_answer_prompt,
            parser=parse_answer_state,
            scorer=simple_scorer,
            temperature=0.3,
            max_tokens=4096,
        ),
    ]
